services:
  ##############################################################################
  # 1) Static files server (using Nginx)
  # We'll serve files from ./static under /images
  ##############################################################################
  static-server:
    image: nginx:alpine
    # We'll map our local ./static to the Nginx default doc root
    volumes:
      - "./static:/usr/share/nginx/html:ro"
    # The default Nginx config in the image listens on port 80
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    # Labels for Traefik
    labels:
      - "traefik.enable=true"
      # We'll match /images prefix
      - "traefik.http.routers.static-files.rule=Host(`rev-proxy.test.lab`)"
      - "traefik.http.routers.static-files.entrypoints=web-secure"
      - "traefik.http.routers.static-files.tls=true"

  ##############################################################################
  # 2) HAProxy with SSL
  ##############################################################################
  haproxy:
    image: haproxy:latest
    profiles: ["haproxy"]
    ports:
      - "443:443"
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      - "./certs:/usr/local/etc/haproxy/certs:ro"
    depends_on:
      - static-server
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8G

  ##############################################################################
  # 3) Nginx with SSL
  ##############################################################################
  nginx:
    image: nginx:latest
    profiles: ["nginx"]
    ports:
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./certs:/etc/nginx/certs:ro"
    depends_on:
        - static-server
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8G

  ##############################################################################
  # 4) Traefik with SSL
  ##############################################################################
  traefik:
    image: traefik:latest
    profiles: ["traefik"]
    command:
      - "--providers.docker=true"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web-secure.http.tls=true"
      # Use a file provider for the cert
      - "--providers.file.directory=/etc/traefik/dynamic"

      # Tuning for performance
      - "--log.level=ERROR"
      - "--accesslog=false"
      - "--serversTransport.maxIdleConnsPerHost=10000"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik_dynamic.yaml:/etc/traefik/dynamic/traefik_dynamic.yaml:ro"
      - "./certs:/etc/traefik/certs:ro"
    depends_on:
      - static-server
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8G
